### PR TITLE
Node version ^10.14 added to engines list

### PR DESCRIPTION
**Pull request by ahmetcetin**
replacing PR #42 (couldn't squash commits on that PR as all changes were made directly in github online). Closing issue #41

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Review by jannyHou — APPROVED** [review]
Cool LGTM 👍

**Comment by ahmetcetin** [comment]
Hi @jannyHou, just checked, the version number in package.json is not changed automatically, shall i update it as well?

**Comment by jannyHou** [comment]
@ahmetcetin Do you want me to release a patch for it?

**Comment by ahmetcetin** [comment]
would be good because it helps to upgrade the package with npm.

**Comment by bajtos** [comment]
Let's make sure our CI build is passing on Travis before publishing this change. See https://github.com/strongloop/loopback-context/pull/44

**Comment by bajtos** [comment]
Published as `loopback-context@3.4.0` 🎉

**Comment by bajtos** [comment]
Thank you @ahmetcetin for the contribution ❤️

**Pull request merged**
