### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yellowred**
as per `package.json` updated supported node versions list

#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@yellowred thank you for the pull request, the changes you are proposing make perfect sense to me! Is there any particular reason why you have closed the pull request? I would be happy to accept it.

**Pull request closed without merging**
