### PR TITLE
[CLOSE THIS][WIP] Completely and permanently replace continuation-local-storage with cls-hooked

### PR DESCRIPTION
**Pull request by josieusa**
**Messed up this PR, replaced with PR #11**
~~Hello, this is a quick and (not so) dirty alternative to PR # 2.~~

~~Rationale:~~
- ~~Personally, I still like more the approach I used in PR # 2, but I just realized it needs further analysis, because I initially forgot to take into account issue async-listener#57.~~
- ~~The quickest and most obvious way to address this is, of course, to get rid of `async-listener`, which already was the long-term goal of my previous PR, anyway. Here it just turned into an immediate goal, that's all.~~
- ~~One trivial way to reach this goal immediately is to completely replace `continuation-local-storage` with `cls-hooked` **quitting any attempt to keep backward compatibility with the former**, which is exactly what I did in this PR and is the difference with my previous PR. This should make the commit `df60f13`no longer necessary, so I reverted it.~~
- ~~`cls-hooked`, however (maybe `continuation-local-storage` too, I don't care), needs to be required before everything else, in order to not fail silently and catastrophically. So, I also gave proper and detailed instructions about how to do this in the README.md~~

~~Anyway, given the very short time I dedicated to this PR, I would consider this a **work-in-progress** for now.~~

~~TODO:~~
- ~~Bump version to 2.0.0-alpha.1 when it's more ready for alpha release.~~

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment "._ok\W+to\W+test._"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by josieusa** [comment]
~~PS
For now, in order to make tests work, after deleting `node_modules` folder and running `npm i`, I had to run (NPM v3):~~
~~`npm r strong-remoting`~~
~~`npm i strong-remoting@3.0.0-alpha.5`~~

~~I suppose this is because loopback PR #2696 maybe hasn't landed in `loopback-context` yet.~~

~~Also, for the same reason, if you test this branch from inside a Loopback app, make sure that `loopback-context` uses the same version of `strong-remoting` as the app.~~

**Comment by josieusa** [comment]
I messed with rebase while trying to sync the fork with the upstream repository. I'm going to replace this with another PR with the same changes by me.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment "._ok\W+to\W+test._"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
