### PR TITLE
Added NodeJS 7 to package.json

### PR DESCRIPTION
**Pull request by xnf**
### Description
Added NodeJS v7 to package.json. 
This way yarn will not complain when node 7 is used.
Tests still pass and the package itself also works on Node 7.

#### Related issues
#29 Add support for Node 7

### Checklist
- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by xnf** [comment]
I close this as I made a PR for wrong stuff, sorry.

**Pull request closed without merging**
